version: '3'

services:
  node:
    build: ./dockerfiles/node/
    volumes:
      - .:/app/
    depends_on:
      - postgres
    command: "npm run start"
    ports:
      - "3000:3000"

  postgres: 
    image: postgres:14.1-alpine
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_ROOT_PASSWORD
      - POSTGRES_PASSWORD=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db:
    driver: local